### ISSUE TITLE
license

### ISSUE THREAD

**Issue by jwijffels** [clips/hades#1]
Hi, 

I would like to understand the licenses you mention in the repository.
Is it correct that the csv files are available under the CC BY-SA 4.0 license and your python code under GPL 3.

thank you

**Comment by stephantul** [comment]
Hello,

You are correct, the code is licensed under GPL 3, the dictionaries (i.e. csv files) are under CC BY-SA 4.0.

**Comment by jwijffels** [comment]
thanks!
